name: validations

on:
  push:
    branches:
      - main
    paths:
      - metadata.schema.json
      - metadata.yaml
  pull_request:
    branches:
      - main
    paths:
      - metadata.schema.json
      - metadata.yaml
  workflow_dispatch:

jobs:
  validate_metadata:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: check metadata file
        run: |
          if [ ! -f metadata.yaml ]; then
            exit 1
          fi
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install -g ajv-cli@5.0.0
      - name: validate metadata file
        run: ajv validate --spec=draft2020 -s metadata.schema.yaml -d metadata.yaml
