name: validations

on:
  pull_request:
    branches:
      - main
      - release/*
  workflow_dispatch:

jobs:
  validate_metadata:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          if [ ! -f metadata.yaml ]; then
            exit 1
          fi
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install -g ajv-cli
      - run: ajv --spec=draft2020 validate -s metadata.schema.json -d metadata.yaml
